
pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir('examble/java'){
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('examble/java'){
                    sh 'mvn test'
                }
            }
            post {
                always {
                    dir('examble/java'){
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Artifact') {
            steps {
                echo "Work!"
            }
        }
    }
}
