
pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir('examble/java'){
                    sh '''
                     export MAVEN_OPTS="-XX:MaxPermSize=128m"
                     mvn -Dmaven.test.skip=true install
                     '''
                }
            }
        }
        stage('Artifact') {
            steps {
                echo "Work!"
            }
        }
    }
}
