version: '3'
services:

  java:
    build: java
    restart: always
    volumes:
      - ../code/java:/usr/src/myapp
    working_dir: /usr/src/myapp
    network_mode: "host"

  python:
    build: python
    restart: always
    volumes:
      - ./python:/usr/src/myapp
    working_dir: /usr/src/myapp
    network_mode: "host"

  web:
    build: web
    volumes:
      - ../code/web:/app/
    restart: always
    network_mode: "host"
